name: CI

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - uses: actions/checkout@v4

      # 2. Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      # 4. Build the site
      - name: Build MkDocs site
        run: mkdocs build --clean

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site        # MkDocs default build folder
          force_orphan: true         # Ensures old files are removed
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
